# Generated by Django 4.0.2 on 2022-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedemo', '0002_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
